# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/jteeuwen/go-bindata",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.5"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.8"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.4.0" #osdk_version_annotation

[[constraint]]
  name="github.com/jteeuwen/go-bindata"
  # Current working master
  revision = "6025e8de665b31fa74ab1a66f2cddd8c0abf887e"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
  
  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name="github.com/jteeuwen/go-bindata"
    unused-packages = false

[[constraint]]
  name = "github.com/openshift/installer"
  branch = "master"

[[constraint]]
  name = "github.com/openshift/library-go"
  branch = "master"
