kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
