apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-vsphere-problem-detector
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: vsphere-cloud-credentials
    namespace: openshift-cluster-storage-operator
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: VSphereProviderSpec
