apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
