# Expose operator metrics
apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: cluster-storage-operator-serving-cert
  labels:
    app: cluster-storage-operator-metrics
  name: cluster-storage-operator-metrics
  namespace: openshift-cluster-storage-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    name: cluster-storage-operator
  sessionAffinity: None
  type: ClusterIP

---

# Expose vsphere-problem-detector metrics
apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: vsphere-problem-detector-serving-cert
  labels:
    app: vsphere-problem-detector-metrics
  name: vsphere-problem-detector-metrics
  namespace: openshift-cluster-storage-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8444
  selector:
    name: cluster-storage-operator
  sessionAffinity: None
  type: ClusterIP
