apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-storage-operator

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operator
rules:
- apiGroups:
  - storage.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operator
subjects:
- kind: ServiceAccount
  name: cluster-storage-operator
roleRef:
  kind: Role
  name: cluster-storage-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operator
roleRef:
  kind: Role
  name: cluster-storage-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - patch
  - update

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
subjects:
- kind: ServiceAccount
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operator
roleRef:
  kind: ClusterRole
  name: cluster-storage-operator
  apiGroup: rbac.authorization.k8s.io
