# Allow reading openshift-config-managed/kube-cloud-config ConfigMap
# with CA bundle.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-ebs-csi-driver-operator-aws-config-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
