kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vsphere-problem-detector-operator-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: vsphere-problem-detector-operator
    namespace: openshift-cluster-storage-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vsphere-problem-detector-operator-clusterrole
