apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: vsphere-problem-detector-serving-cert
  labels:
    app: vsphere-problem-detector-metrics
  name: vsphere-problem-detector-metrics
  namespace: openshift-cluster-storage-operator
spec:
  ports:
  - name: vsphere-metrics
    port: 8444
    protocol: TCP
    targetPort: vsphere-metrics
  selector:
    name: vsphere-problem-detector-operator
  sessionAffinity: None
  type: ClusterIP
